/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class asm_Native */

#ifndef _Included_asm_Native
#define _Included_asm_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     asm_Native
 * Method:    GetConsoleMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_asm_Native_GetConsoleMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     asm_Native
 * Method:    SetConsoleMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_asm_Native_SetConsoleMode
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
